import { Point } from '../entities/point.js';
import { Entity } from '../entities/entity.js';
import { EndBlock } from './endblk.js';
import { DXFFile } from '../lib/dxf/dxfFile.js';
import { BoundingBox } from '../lib/boundingBox.js';
import { Strings } from '../lib/strings.js';
import { Input, PromptOptions } from '../lib/inputManager.js';
import { Flags } from '../properties/flags.js';
import { Property } from '../properties/property.js';
import { AddState, RemoveState } from '../lib/stateManager.js';

import { DesignCore } from '../designCore.js';
import { Utils } from '../lib/utils.js';

/**
 * Block Entity Class
 * @extends Entity
 */
export class Block extends Entity {
  static type = 'Block';

  /**
   * Create a Block Entity
   * @param {Array} data
   */
  constructor(data) {
    super(data);
    this.name = '';
    this.points = [new Point()];
    // Store the block record handle and endblk handle for use when writing to dxf file
    this.blockRecordHandle = data?.blockRecordHandle;
    this.endblkHandle = data?.endblkHandle;

    Object.defineProperty(this, 'flags', {
      value: new Flags(),
      writable: true,
    });

    Object.defineProperty(this, 'entities', {
      value: [],
      writable: true,
    });

    if (data) {
      if (data.hasOwnProperty('name') || data.hasOwnProperty('2')) {
        // DXF Groupcode 2 - Block Name
        this.name = data.name || data[2];
      }

      if (data.hasOwnProperty('entities')) {
        this.entities = data.entities;
      }

      if (data.hasOwnProperty('flags') || data.hasOwnProperty('70')) {
        // DXF Groupcode 70 - Block-type flags (bit-coded):
        // 0 = Indicates none of the following flags apply
        // 1 = This is an anonymous block generated by hatching, associative dimensioning, other internal operations, or an application
        // 2 = This block has non-constant attribute definitions (this bit is not set if the block has any attribute definitions that are constant, or has no attribute definitions at all)
        // 4 = This block is an external reference (xref)
        // 8 = This block is an xref overlay
        // 16 = This block is externally dependent
        // 32 = This is a resolved external reference, or dependent of an external reference (ignored on input)
        // 64 = This definition is a referenced external reference (ignored on input)

        this.flags.setFlagValue(Property.loadValue([data.flags, data[70]], 0));
      }
    }
  }

  /**
   * Register the command
   * @return {Object}
   * command = name of the command
   * shortcut = shortcut for the command
   * type = type to group command in toolbars (omitted if not shown)
   */
  static register() {
    const command = { command: 'Block', shortcut: 'B' };
    return command;
  }

  /**
   * Execute method
   * executes the workflow, requesting input required to create an entity
   */
  async execute() {
    try {
      // set a name
      const defaultName = `Block-${DesignCore.Scene.blockManager.itemCount()}`;
      const nameOp = new PromptOptions(Strings.Input.NAME, [Input.Type.STRING], [], defaultName);
      const selectedName = await DesignCore.Scene.inputManager.requestInput(nameOp);

      // get the insertion point
      const op2 = new PromptOptions(Strings.Input.BASEPOINT, [
        Input.Type.POINT,
      ]);
      const insertPoint = await DesignCore.Scene.inputManager.requestInput(op2);

      // get the block entities
      const op = new PromptOptions(Strings.Input.SELECTIONSET, [
        Input.Type.SELECTIONSET,
      ]);

      if (!DesignCore.Scene.selectionManager.selectionSet.selectionSet.length) {
        await DesignCore.Scene.inputManager.requestInput(op);
      }

      // create block
      const block = DesignCore.Scene.blockManager.addItem({ name: selectedName });
      // get a copy of the selection set
      const selections = DesignCore.Scene.selectionManager.selectionSet.selectionSet.slice();
      // sort the selection in descending order
      selections.sort((a, b) => b - a);
      // array to hold state changes
      const stateChanges = [];

      // move selected items from scene to block
      selections.forEach((index) => {
        const item = DesignCore.Scene.entities.get(index);
        // remove item from scene
        const copyOfItem = Utils.cloneObject(item);
        // assign a fresh handle — the block item is a new entity distinct from the scene entity
        copyOfItem.setProperty('handle', DesignCore.HandleManager.next());
        // adjust the items points to reflect the insert point
        const delta = new Point(-insertPoint.x, -insertPoint.y);
        if (copyOfItem.points?.length) {
          const points = copyOfItem.points.map((p) => new Point(p.x, p.y, p.bulge, p.sequence).add(delta));
          copyOfItem.setProperty('points', points);
        }
        block.entities.push(copyOfItem);
        const stateChangeRemove = new RemoveState(item);
        stateChanges.push(stateChangeRemove);
      });

      // define insert data
      const insertData = {
        type: 'Insert',
        points: [new Point(insertPoint.x, insertPoint.y)],
        blockName: selectedName,
      };

      const insert = DesignCore.CommandManager.createNew(insertData.type, insertData);
      const stateChangeAdd = new AddState(insert);
      stateChanges.push(stateChangeAdd);

      // commit the changes to the scene
      DesignCore.Scene.commit(stateChanges);

      DesignCore.Scene.inputManager.executeCommand();
    } catch (err) {
      Logging.instance.error(`${this.type} - ${err}`);
    }
  }

  /**
   * Preview the entity during creation
   */
  preview() { }

  /**
   * Write the entity to file in the dxf format
   * @param {DXFFile} file
   */
  dxf(file) {
    file.writeGroupCode('0', 'BLOCK');
    file.writeGroupCode('5', this.getProperty('handle'), DXFFile.Version.R2000); // Handle
    file.writeGroupCode('100', 'AcDbEntity', DXFFile.Version.R2000);
    file.writeGroupCode('8', this.getProperty('layer'));
    file.writeGroupCode('100', 'AcDbBlockBegin', DXFFile.Version.R2000);
    file.writeGroupCode('2', this.name);
    file.writeGroupCode('70', this.flags.getFlagValue());
    file.writeGroupCode('10', this.points[0].x);
    file.writeGroupCode('20', this.points[0].y);
    file.writeGroupCode('30', 0.0);
    file.writeGroupCode('3', this.name); // Name again
    file.writeGroupCode('1', '');

    for (let i = 0; i < this.entities.length; i++) {
      this.entities[i].dxf(file);
    }

    const endblk = new EndBlock({ handle: this.endblkHandle });
    endblk.dxf(file);
  }

  /**
   * Clear entities from the block
   */
  clearEntities() {
    this.entities = [];
  }

  /**
   * Add an entity to the block
   * @param {Object} entity
   */
  addEntity(entity) {
    this.entities.push(entity);
  }

  /**
   * Get snap points
   * @param {Point} mousePoint
   * @param {number} delta
   * @return {Array} - array of snap points
   */
  snaps(mousePoint, delta) {
    const snaps = [];

    if (!this.entities.length) {
      // nothing to draw
      return snaps;
    }

    for (let item = 0; item < this.entities.length; item++) {
      // collect the child item snaps
      const itemSnaps = this.entities[item].snaps(mousePoint, delta);
      snaps.push(...itemSnaps);
    }

    return snaps;
  }

  /**
   * Get closest point on entity
   * @param {Point} P
   * @return {Array} - [Point, distance]
   */
  closestPoint(P) {
    let distance = Infinity;
    let minPnt = P;

    if (!this.entities.length) {
      // nothing to draw
      return [minPnt, distance];
    }

    for (let idx = 0; idx < this.entities.length; idx++) {
      const itemClosestPoint = this.entities[idx].closestPoint(P);
      const itemPnt = itemClosestPoint[0];
      const itemDist = itemClosestPoint[1];

      if (itemDist < distance) {
        distance = itemDist;
        minPnt = itemPnt;
      }
    }

    return [minPnt, distance];
  }

  /**
   * Return boundingbox for entity
   * @return {BoundingBox}
   */
  boundingBox() {
    let xmin = Infinity;
    let xmax = -Infinity;
    let ymin = Infinity;
    let ymax = -Infinity;

    for (let idx = 0; idx < this.entities.length; idx++) {
      const itemBoundingBox = this.entities[idx].boundingBox();

      xmin = Math.min(xmin, itemBoundingBox.xMin);
      xmax = Math.max(xmax, itemBoundingBox.xMax);
      ymin = Math.min(ymin, itemBoundingBox.yMin);
      ymax = Math.max(ymax, itemBoundingBox.yMax);
    }

    const topLeft = new Point(xmin, ymax);
    const bottomRight = new Point(xmax, ymin);

    return new BoundingBox(topLeft, bottomRight);
  }

  /**
   * Determine if the entity is touch the selection window
   * @param {Object} selection - {min: Point, max: Point}
   * @return {boolean} true if touched
   */
  touched(selection) {
    for (let idx = 0; idx < this.entities.length; idx++) {
      const touched = this.entities[idx].touched(selection);
      if (touched) {
        return true;
      }
    }

    return false;
  }
}
